### ISSUE TITLE
Tela - Adicionar voo: Total Hours e Price 

### ISSUE THREAD

**Issue by nathalieSantos** [gabriel-codes/solutis-react-final#15]
Total Hours: Não tem indicação de campo obrigatório, apesar de retornar para o campo quando tem ou ausência de preenchimento
 ![toth](https://user-images.githubusercontent.com/75738919/104773114-48c98300-5753-11eb-9b4c-4e7d09ca6468.png)
 *Print ao clicar em submit*
	
Price: Só aparece a mensagem "Preencha esse campo" ao dar enter no campo Adult, quando o mesmo é feito em Child e Infant, retorna para o campo Adult e a mensagem é exibida 

---
![submit](https://user-images.githubusercontent.com/75738919/104773144-53841800-5753-11eb-90a6-0072068eec0f.png)
*Print ao clicar em submit*

----
![alet](https://user-images.githubusercontent.com/75738919/104773129-4cf5a080-5753-11eb-9cbc-615436838b92.png)
*Print com enter*

**Comment by zJoaoP** [comment]
Sobre o campo totalHours, ele foi convertido recentemente para readonly e seu valor é calculado de acordo com a rota preenchida no formulário. 

As mudanças já estão na branch "develop".

**Comment by nathalieSantos** [comment]
Acabei de ver essa alteração

**Comment by zJoaoP** [comment]
> Acabei de ver essa alteração

Sobre os campos de preço, peço que reavalie na versão atual do código.
Não consegui entender muito bem qual o problema com eles.

**Comment by nathalieSantos** [comment]
Código reavaliado, o price já está com a validação de campo obrigatório
