### ISSUE TITLE
Tela - Adicionar voo: Deposite

### ISSUE THREAD

**Issue by nathalieSantos** [gabriel-codes/solutis-react-final#16]
O campo Deposite aceita letras e não somente números 
(**SUGESTÃO**)  Colocar um placeHolder no campo 

![deposite](https://user-images.githubusercontent.com/75738919/104776777-5e41ab80-5759-11eb-8f4e-8118f8b4aa0b.png)

**Comment by zJoaoP** [comment]
Corrigo. Atualmente, o campo é verificado com a propriedade "pattern" e exige que o valor atenda aos mesmos critérios dos campos de preço (Expressão regular utilizada: "\d+(,\d{2})")

**Comment by nathalieSantos** [comment]
verificado. tudo ok
