### ISSUE TITLE
Tela - Adicionar Extra: Não possui limites de caractere para tamanho dos textos

### ISSUE THREAD

**Issue by rodrigosilvestre** [gabriel-codes/solutis-react-final#5]
![errortextoiliminato](https://user-images.githubusercontent.com/58074589/104744497-b792e600-572b-11eb-8721-499685dc579e.png)

O error acaba ocasionando uma quebra de tabela, e os itens Traduzir, Lupa, Editar e Excluir ficam fora da tela

**Comment by rodrigosilvestre** [comment]
O mesmo acontece para o preço

**Comment by monteirovitor** [comment]
Correções foram aplicadas no commit: 9da7fb4ba7088333c3732e82fb8632025e8121e4 , limite de caracteres passa a ser 40 e preço 100000.
