### ISSUE TITLE
Tela - Adicionar Extra: Não possui nenhuma barreira contra valores negativos para o preço, possibilitando a adição de extras com o preço negativo 

### ISSUE THREAD

**Issue by rodrigosilvestre** [gabriel-codes/solutis-react-final#6]
![PrecoNegativopng](https://user-images.githubusercontent.com/58074589/104744956-430c7700-572c-11eb-8d1b-0732a5f197e6.png)

**Comment by monteirovitor** [comment]
Correção aplicada no commit: 9da7fb4ba7088333c3732e82fb8632025e8121e4 , intervalo válido passa a ser 0 a 100000.
