### ISSUE TITLE
Tela - Adicionar voo: Adicionar novo voo

### ISSUE THREAD

**Issue by nathalieSantos** [gabriel-codes/solutis-react-final#8]
Ao adicionar outro voo os dados inseridos anteriormente são persistidos.
(**SUGESTÃO**) Zerar os campos ao clicar em ADD 

![2](https://user-images.githubusercontent.com/75738919/104750203-8538b700-5732-11eb-8591-1e7c5e8b1452.png)
*Print da tela ao clicar em adicionar logo após ter adicionado um voo*

**Comment by zJoaoP** [comment]
O comportamento foi corrigido e a sugestão foi implementada.
