### ISSUE TITLE
Tela: Lista de voos - A tabela de voos está sendo preenchida com voos sem horários (OBSERVAÇÃO)

### ISSUE THREAD

**Issue by philipe02** [gabriel-codes/solutis-react-final#9]
![EditarVoo](https://user-images.githubusercontent.com/28534813/104755997-f0d25280-5739-11eb-965f-944ad5f67e40.png)

**Comment by zJoaoP** [comment]
O erro ocorreu por conta da mudança de nome do atributo "time" para "checkin". No momento da captura de tela, a mudança só havia sido efetuada na API. (Atualmente, os campos estão sendo preenchidos corretamente na tela de edição)

![image](https://user-images.githubusercontent.com/43040984/104774505-8d561e00-5755-11eb-8bab-99a3235e78fb.png)

Algumas outras mudanças foram realizadas no formulário e já se encontram na branch "develop".

**Comment by philipe02** [comment]
Tranquilo, chequei aqui e foi resolvido, vou fechar a issue.
